name: Test exercises

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test exercises
        run: |
          set -e
          EXIT_CODE=0
          find . -name go.mod -execdir sh -c 'go test ./... | tee /dev/stderr | grep -q FAIL [ $? -ne 0]' \;
          exit $EXIT_CODE
