name: Test exercises

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test exercises
        run: |
          set -e
          EXIT_CODE=0
          for dir in $(find . -name go.mod -execdir pwd \;); do
              (cd "$dir" && go test ./... | tee /dev/stderr) || EXIT_CODE=1
          done
          exit $EXIT_CODE
